{
 "title": "Punchr Health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Punchr Honeypot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"punchr_honeypot\"}"
    }
   ]
  },
  {
   "title": "Punchr Server",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"punchr_server\"}"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Punchr Honeypot Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"punchr_honeypot\"}"
    }
   ]
  },
  {
   "title": "Punchr Server Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"punchr_server\"}"
    }
   ]
  },
  {
   "title": "Prometheus Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Punchr Honeypot CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"punchr_honeypot\"}[5m])"
    }
   ]
  },
  {
   "title": "Punchr Server CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"punchr_server\"}[5m])"
    }
   ]
  },
  {
   "title": "Prometheus CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"prometheus\"}[5m])"
    }
   ]
  },
  { "title": "Punchr Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Peer Allocation Query Durations in Seconds (single)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_allocation_query_duration_seconds_bucket{job=\"punchr_server\",success=\"true\",type=\"single\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Peer Allocation Query Durations in Seconds (all)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_allocation_query_duration_seconds_bucket{job=\"punchr_server\",success=\"true\",type=\"all\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gRPC calls per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{job=\"punchr_server\"}[5m])",
     "legendFormat": "{{grpc_method}} - {{grpc_code}}"
    }
   ]
  },
  {
   "title": "GetAddrInfo Durations in Seconds",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grpc_server_handling_seconds_bucket{grpc_method=\"GetAddrInfo\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "TrackHolePunch Durations in Seconds",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grpc_server_handling_seconds_bucket{grpc_method=\"TrackHolePunch\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GetAddrInfo Durations in Seconds",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handling_seconds_bucket{grpc_method=\"GetAddrInfo\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "TrackHolePunch Durations in Seconds",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handling_seconds_bucket{grpc_method=\"TrackHolePunch\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}