FROM golang:1.19 AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 make build-client

# Create lightweight container to run nebula
FROM alpine:latest

WORKDIR /root

COPY --from=builder /build/dist/punchrclient /usr/local/bin/punchr
CMD punchr
