// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ConnectionEvents           string
	HolePunchResults           string
	IPAddresses                string
	MultiAddresses             string
	MultiAddressesXIPAddresses string
	PeerLogs                   string
	Peers                      string
}{
	ConnectionEvents:           "connection_events",
	HolePunchResults:           "hole_punch_results",
	IPAddresses:                "ip_addresses",
	MultiAddresses:             "multi_addresses",
	MultiAddressesXIPAddresses: "multi_addresses_x_ip_addresses",
	PeerLogs:                   "peer_logs",
	Peers:                      "peers",
}
