// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ConnectionEvent is an object representing the database table.
type ConnectionEvent struct {
	ID                 int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	LocalID            int64     `boil:"local_id" json:"local_id" toml:"local_id" yaml:"local_id"`
	RemoteID           int64     `boil:"remote_id" json:"remote_id" toml:"remote_id" yaml:"remote_id"`
	ConnMultiAddressID int64     `boil:"conn_multi_address_id" json:"conn_multi_address_id" toml:"conn_multi_address_id" yaml:"conn_multi_address_id"`
	OpenedAt           time.Time `boil:"opened_at" json:"opened_at" toml:"opened_at" yaml:"opened_at"`
	CreatedAt          time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *connectionEventR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L connectionEventL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ConnectionEventColumns = struct {
	ID                 string
	LocalID            string
	RemoteID           string
	ConnMultiAddressID string
	OpenedAt           string
	CreatedAt          string
}{
	ID:                 "id",
	LocalID:            "local_id",
	RemoteID:           "remote_id",
	ConnMultiAddressID: "conn_multi_address_id",
	OpenedAt:           "opened_at",
	CreatedAt:          "created_at",
}

var ConnectionEventTableColumns = struct {
	ID                 string
	LocalID            string
	RemoteID           string
	ConnMultiAddressID string
	OpenedAt           string
	CreatedAt          string
}{
	ID:                 "connection_events.id",
	LocalID:            "connection_events.local_id",
	RemoteID:           "connection_events.remote_id",
	ConnMultiAddressID: "connection_events.conn_multi_address_id",
	OpenedAt:           "connection_events.opened_at",
	CreatedAt:          "connection_events.created_at",
}

// Generated where

var ConnectionEventWhere = struct {
	ID                 whereHelperint
	LocalID            whereHelperint64
	RemoteID           whereHelperint64
	ConnMultiAddressID whereHelperint64
	OpenedAt           whereHelpertime_Time
	CreatedAt          whereHelpertime_Time
}{
	ID:                 whereHelperint{field: "\"connection_events\".\"id\""},
	LocalID:            whereHelperint64{field: "\"connection_events\".\"local_id\""},
	RemoteID:           whereHelperint64{field: "\"connection_events\".\"remote_id\""},
	ConnMultiAddressID: whereHelperint64{field: "\"connection_events\".\"conn_multi_address_id\""},
	OpenedAt:           whereHelpertime_Time{field: "\"connection_events\".\"opened_at\""},
	CreatedAt:          whereHelpertime_Time{field: "\"connection_events\".\"created_at\""},
}

// ConnectionEventRels is where relationship names are stored.
var ConnectionEventRels = struct {
	Local            string
	ConnMultiAddress string
	Remote           string
	MultiAddresses   string
}{
	Local:            "Local",
	ConnMultiAddress: "ConnMultiAddress",
	Remote:           "Remote",
	MultiAddresses:   "MultiAddresses",
}

// connectionEventR is where relationships are stored.
type connectionEventR struct {
	Local            *Peer             `boil:"Local" json:"Local" toml:"Local" yaml:"Local"`
	ConnMultiAddress *MultiAddress     `boil:"ConnMultiAddress" json:"ConnMultiAddress" toml:"ConnMultiAddress" yaml:"ConnMultiAddress"`
	Remote           *Peer             `boil:"Remote" json:"Remote" toml:"Remote" yaml:"Remote"`
	MultiAddresses   MultiAddressSlice `boil:"MultiAddresses" json:"MultiAddresses" toml:"MultiAddresses" yaml:"MultiAddresses"`
}

// NewStruct creates a new relationship struct
func (*connectionEventR) NewStruct() *connectionEventR {
	return &connectionEventR{}
}

func (r *connectionEventR) GetLocal() *Peer {
	if r == nil {
		return nil
	}
	return r.Local
}

func (r *connectionEventR) GetConnMultiAddress() *MultiAddress {
	if r == nil {
		return nil
	}
	return r.ConnMultiAddress
}

func (r *connectionEventR) GetRemote() *Peer {
	if r == nil {
		return nil
	}
	return r.Remote
}

func (r *connectionEventR) GetMultiAddresses() MultiAddressSlice {
	if r == nil {
		return nil
	}
	return r.MultiAddresses
}

// connectionEventL is where Load methods for each relationship are stored.
type connectionEventL struct{}

var (
	connectionEventAllColumns            = []string{"id", "local_id", "remote_id", "conn_multi_address_id", "opened_at", "created_at"}
	connectionEventColumnsWithoutDefault = []string{"local_id", "remote_id", "conn_multi_address_id", "opened_at", "created_at"}
	connectionEventColumnsWithDefault    = []string{"id"}
	connectionEventPrimaryKeyColumns     = []string{"id"}
	connectionEventGeneratedColumns      = []string{"id"}
)

type (
	// ConnectionEventSlice is an alias for a slice of pointers to ConnectionEvent.
	// This should almost always be used instead of []ConnectionEvent.
	ConnectionEventSlice []*ConnectionEvent
	// ConnectionEventHook is the signature for custom ConnectionEvent hook methods
	ConnectionEventHook func(context.Context, boil.ContextExecutor, *ConnectionEvent) error

	connectionEventQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	connectionEventType                 = reflect.TypeOf(&ConnectionEvent{})
	connectionEventMapping              = queries.MakeStructMapping(connectionEventType)
	connectionEventPrimaryKeyMapping, _ = queries.BindMapping(connectionEventType, connectionEventMapping, connectionEventPrimaryKeyColumns)
	connectionEventInsertCacheMut       sync.RWMutex
	connectionEventInsertCache          = make(map[string]insertCache)
	connectionEventUpdateCacheMut       sync.RWMutex
	connectionEventUpdateCache          = make(map[string]updateCache)
	connectionEventUpsertCacheMut       sync.RWMutex
	connectionEventUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var connectionEventAfterSelectHooks []ConnectionEventHook

var connectionEventBeforeInsertHooks []ConnectionEventHook
var connectionEventAfterInsertHooks []ConnectionEventHook

var connectionEventBeforeUpdateHooks []ConnectionEventHook
var connectionEventAfterUpdateHooks []ConnectionEventHook

var connectionEventBeforeDeleteHooks []ConnectionEventHook
var connectionEventAfterDeleteHooks []ConnectionEventHook

var connectionEventBeforeUpsertHooks []ConnectionEventHook
var connectionEventAfterUpsertHooks []ConnectionEventHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ConnectionEvent) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range connectionEventAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ConnectionEvent) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range connectionEventBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ConnectionEvent) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range connectionEventAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ConnectionEvent) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range connectionEventBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ConnectionEvent) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range connectionEventAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ConnectionEvent) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range connectionEventBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ConnectionEvent) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range connectionEventAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ConnectionEvent) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range connectionEventBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ConnectionEvent) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range connectionEventAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddConnectionEventHook registers your hook function for all future operations.
func AddConnectionEventHook(hookPoint boil.HookPoint, connectionEventHook ConnectionEventHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		connectionEventAfterSelectHooks = append(connectionEventAfterSelectHooks, connectionEventHook)
	case boil.BeforeInsertHook:
		connectionEventBeforeInsertHooks = append(connectionEventBeforeInsertHooks, connectionEventHook)
	case boil.AfterInsertHook:
		connectionEventAfterInsertHooks = append(connectionEventAfterInsertHooks, connectionEventHook)
	case boil.BeforeUpdateHook:
		connectionEventBeforeUpdateHooks = append(connectionEventBeforeUpdateHooks, connectionEventHook)
	case boil.AfterUpdateHook:
		connectionEventAfterUpdateHooks = append(connectionEventAfterUpdateHooks, connectionEventHook)
	case boil.BeforeDeleteHook:
		connectionEventBeforeDeleteHooks = append(connectionEventBeforeDeleteHooks, connectionEventHook)
	case boil.AfterDeleteHook:
		connectionEventAfterDeleteHooks = append(connectionEventAfterDeleteHooks, connectionEventHook)
	case boil.BeforeUpsertHook:
		connectionEventBeforeUpsertHooks = append(connectionEventBeforeUpsertHooks, connectionEventHook)
	case boil.AfterUpsertHook:
		connectionEventAfterUpsertHooks = append(connectionEventAfterUpsertHooks, connectionEventHook)
	}
}

// One returns a single connectionEvent record from the query.
func (q connectionEventQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ConnectionEvent, error) {
	o := &ConnectionEvent{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for connection_events")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ConnectionEvent records from the query.
func (q connectionEventQuery) All(ctx context.Context, exec boil.ContextExecutor) (ConnectionEventSlice, error) {
	var o []*ConnectionEvent

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ConnectionEvent slice")
	}

	if len(connectionEventAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ConnectionEvent records in the query.
func (q connectionEventQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count connection_events rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q connectionEventQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if connection_events exists")
	}

	return count > 0, nil
}

// Local pointed to by the foreign key.
func (o *ConnectionEvent) Local(mods ...qm.QueryMod) peerQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.LocalID),
	}

	queryMods = append(queryMods, mods...)

	return Peers(queryMods...)
}

// ConnMultiAddress pointed to by the foreign key.
func (o *ConnectionEvent) ConnMultiAddress(mods ...qm.QueryMod) multiAddressQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ConnMultiAddressID),
	}

	queryMods = append(queryMods, mods...)

	return MultiAddresses(queryMods...)
}

// Remote pointed to by the foreign key.
func (o *ConnectionEvent) Remote(mods ...qm.QueryMod) peerQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.RemoteID),
	}

	queryMods = append(queryMods, mods...)

	return Peers(queryMods...)
}

// MultiAddresses retrieves all the multi_address's MultiAddresses with an executor.
func (o *ConnectionEvent) MultiAddresses(mods ...qm.QueryMod) multiAddressQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"connection_events_x_multi_addresses\" on \"multi_addresses\".\"id\" = \"connection_events_x_multi_addresses\".\"multi_address_id\""),
		qm.Where("\"connection_events_x_multi_addresses\".\"connection_event_id\"=?", o.ID),
	)

	return MultiAddresses(queryMods...)
}

// LoadLocal allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (connectionEventL) LoadLocal(ctx context.Context, e boil.ContextExecutor, singular bool, maybeConnectionEvent interface{}, mods queries.Applicator) error {
	var slice []*ConnectionEvent
	var object *ConnectionEvent

	if singular {
		var ok bool
		object, ok = maybeConnectionEvent.(*ConnectionEvent)
		if !ok {
			object = new(ConnectionEvent)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeConnectionEvent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeConnectionEvent))
			}
		}
	} else {
		s, ok := maybeConnectionEvent.(*[]*ConnectionEvent)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeConnectionEvent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeConnectionEvent))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &connectionEventR{}
		}
		args = append(args, object.LocalID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &connectionEventR{}
			}

			for _, a := range args {
				if a == obj.LocalID {
					continue Outer
				}
			}

			args = append(args, obj.LocalID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`peers`),
		qm.WhereIn(`peers.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Peer")
	}

	var resultSlice []*Peer
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Peer")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for peers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for peers")
	}

	if len(connectionEventAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Local = foreign
		if foreign.R == nil {
			foreign.R = &peerR{}
		}
		foreign.R.LocalConnectionEvents = append(foreign.R.LocalConnectionEvents, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.LocalID == foreign.ID {
				local.R.Local = foreign
				if foreign.R == nil {
					foreign.R = &peerR{}
				}
				foreign.R.LocalConnectionEvents = append(foreign.R.LocalConnectionEvents, local)
				break
			}
		}
	}

	return nil
}

// LoadConnMultiAddress allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (connectionEventL) LoadConnMultiAddress(ctx context.Context, e boil.ContextExecutor, singular bool, maybeConnectionEvent interface{}, mods queries.Applicator) error {
	var slice []*ConnectionEvent
	var object *ConnectionEvent

	if singular {
		var ok bool
		object, ok = maybeConnectionEvent.(*ConnectionEvent)
		if !ok {
			object = new(ConnectionEvent)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeConnectionEvent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeConnectionEvent))
			}
		}
	} else {
		s, ok := maybeConnectionEvent.(*[]*ConnectionEvent)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeConnectionEvent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeConnectionEvent))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &connectionEventR{}
		}
		args = append(args, object.ConnMultiAddressID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &connectionEventR{}
			}

			for _, a := range args {
				if a == obj.ConnMultiAddressID {
					continue Outer
				}
			}

			args = append(args, obj.ConnMultiAddressID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`multi_addresses`),
		qm.WhereIn(`multi_addresses.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load MultiAddress")
	}

	var resultSlice []*MultiAddress
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice MultiAddress")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for multi_addresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for multi_addresses")
	}

	if len(connectionEventAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ConnMultiAddress = foreign
		if foreign.R == nil {
			foreign.R = &multiAddressR{}
		}
		foreign.R.ConnMultiAddressConnectionEvents = append(foreign.R.ConnMultiAddressConnectionEvents, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ConnMultiAddressID == foreign.ID {
				local.R.ConnMultiAddress = foreign
				if foreign.R == nil {
					foreign.R = &multiAddressR{}
				}
				foreign.R.ConnMultiAddressConnectionEvents = append(foreign.R.ConnMultiAddressConnectionEvents, local)
				break
			}
		}
	}

	return nil
}

// LoadRemote allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (connectionEventL) LoadRemote(ctx context.Context, e boil.ContextExecutor, singular bool, maybeConnectionEvent interface{}, mods queries.Applicator) error {
	var slice []*ConnectionEvent
	var object *ConnectionEvent

	if singular {
		var ok bool
		object, ok = maybeConnectionEvent.(*ConnectionEvent)
		if !ok {
			object = new(ConnectionEvent)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeConnectionEvent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeConnectionEvent))
			}
		}
	} else {
		s, ok := maybeConnectionEvent.(*[]*ConnectionEvent)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeConnectionEvent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeConnectionEvent))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &connectionEventR{}
		}
		args = append(args, object.RemoteID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &connectionEventR{}
			}

			for _, a := range args {
				if a == obj.RemoteID {
					continue Outer
				}
			}

			args = append(args, obj.RemoteID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`peers`),
		qm.WhereIn(`peers.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Peer")
	}

	var resultSlice []*Peer
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Peer")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for peers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for peers")
	}

	if len(connectionEventAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Remote = foreign
		if foreign.R == nil {
			foreign.R = &peerR{}
		}
		foreign.R.RemoteConnectionEvents = append(foreign.R.RemoteConnectionEvents, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.RemoteID == foreign.ID {
				local.R.Remote = foreign
				if foreign.R == nil {
					foreign.R = &peerR{}
				}
				foreign.R.RemoteConnectionEvents = append(foreign.R.RemoteConnectionEvents, local)
				break
			}
		}
	}

	return nil
}

// LoadMultiAddresses allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (connectionEventL) LoadMultiAddresses(ctx context.Context, e boil.ContextExecutor, singular bool, maybeConnectionEvent interface{}, mods queries.Applicator) error {
	var slice []*ConnectionEvent
	var object *ConnectionEvent

	if singular {
		var ok bool
		object, ok = maybeConnectionEvent.(*ConnectionEvent)
		if !ok {
			object = new(ConnectionEvent)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeConnectionEvent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeConnectionEvent))
			}
		}
	} else {
		s, ok := maybeConnectionEvent.(*[]*ConnectionEvent)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeConnectionEvent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeConnectionEvent))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &connectionEventR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &connectionEventR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.Select("\"multi_addresses\".\"id\", \"multi_addresses\".\"asn\", \"multi_addresses\".\"is_cloud\", \"multi_addresses\".\"is_relay\", \"multi_addresses\".\"is_public\", \"multi_addresses\".\"addr\", \"multi_addresses\".\"has_many_addrs\", \"multi_addresses\".\"country\", \"multi_addresses\".\"continent\", \"multi_addresses\".\"maddr\", \"multi_addresses\".\"updated_at\", \"multi_addresses\".\"created_at\", \"a\".\"connection_event_id\""),
		qm.From("\"multi_addresses\""),
		qm.InnerJoin("\"connection_events_x_multi_addresses\" as \"a\" on \"multi_addresses\".\"id\" = \"a\".\"multi_address_id\""),
		qm.WhereIn("\"a\".\"connection_event_id\" in ?", args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load multi_addresses")
	}

	var resultSlice []*MultiAddress

	var localJoinCols []int
	for results.Next() {
		one := new(MultiAddress)
		var localJoinCol int

		err = results.Scan(&one.ID, &one.Asn, &one.IsCloud, &one.IsRelay, &one.IsPublic, &one.Addr, &one.HasManyAddrs, &one.Country, &one.Continent, &one.Maddr, &one.UpdatedAt, &one.CreatedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for multi_addresses")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice multi_addresses")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on multi_addresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for multi_addresses")
	}

	if len(multiAddressAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.MultiAddresses = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &multiAddressR{}
			}
			foreign.R.ConnectionEvents = append(foreign.R.ConnectionEvents, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.MultiAddresses = append(local.R.MultiAddresses, foreign)
				if foreign.R == nil {
					foreign.R = &multiAddressR{}
				}
				foreign.R.ConnectionEvents = append(foreign.R.ConnectionEvents, local)
				break
			}
		}
	}

	return nil
}

// SetLocal of the connectionEvent to the related item.
// Sets o.R.Local to related.
// Adds o to related.R.LocalConnectionEvents.
func (o *ConnectionEvent) SetLocal(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Peer) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"connection_events\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"local_id"}),
		strmangle.WhereClause("\"", "\"", 2, connectionEventPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.LocalID = related.ID
	if o.R == nil {
		o.R = &connectionEventR{
			Local: related,
		}
	} else {
		o.R.Local = related
	}

	if related.R == nil {
		related.R = &peerR{
			LocalConnectionEvents: ConnectionEventSlice{o},
		}
	} else {
		related.R.LocalConnectionEvents = append(related.R.LocalConnectionEvents, o)
	}

	return nil
}

// SetConnMultiAddress of the connectionEvent to the related item.
// Sets o.R.ConnMultiAddress to related.
// Adds o to related.R.ConnMultiAddressConnectionEvents.
func (o *ConnectionEvent) SetConnMultiAddress(ctx context.Context, exec boil.ContextExecutor, insert bool, related *MultiAddress) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"connection_events\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"conn_multi_address_id"}),
		strmangle.WhereClause("\"", "\"", 2, connectionEventPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ConnMultiAddressID = related.ID
	if o.R == nil {
		o.R = &connectionEventR{
			ConnMultiAddress: related,
		}
	} else {
		o.R.ConnMultiAddress = related
	}

	if related.R == nil {
		related.R = &multiAddressR{
			ConnMultiAddressConnectionEvents: ConnectionEventSlice{o},
		}
	} else {
		related.R.ConnMultiAddressConnectionEvents = append(related.R.ConnMultiAddressConnectionEvents, o)
	}

	return nil
}

// SetRemote of the connectionEvent to the related item.
// Sets o.R.Remote to related.
// Adds o to related.R.RemoteConnectionEvents.
func (o *ConnectionEvent) SetRemote(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Peer) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"connection_events\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"remote_id"}),
		strmangle.WhereClause("\"", "\"", 2, connectionEventPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.RemoteID = related.ID
	if o.R == nil {
		o.R = &connectionEventR{
			Remote: related,
		}
	} else {
		o.R.Remote = related
	}

	if related.R == nil {
		related.R = &peerR{
			RemoteConnectionEvents: ConnectionEventSlice{o},
		}
	} else {
		related.R.RemoteConnectionEvents = append(related.R.RemoteConnectionEvents, o)
	}

	return nil
}

// AddMultiAddresses adds the given related objects to the existing relationships
// of the connection_event, optionally inserting them as new records.
// Appends related to o.R.MultiAddresses.
// Sets related.R.ConnectionEvents appropriately.
func (o *ConnectionEvent) AddMultiAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*MultiAddress) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"connection_events_x_multi_addresses\" (\"connection_event_id\", \"multi_address_id\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &connectionEventR{
			MultiAddresses: related,
		}
	} else {
		o.R.MultiAddresses = append(o.R.MultiAddresses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &multiAddressR{
				ConnectionEvents: ConnectionEventSlice{o},
			}
		} else {
			rel.R.ConnectionEvents = append(rel.R.ConnectionEvents, o)
		}
	}
	return nil
}

// SetMultiAddresses removes all previously related items of the
// connection_event replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.ConnectionEvents's MultiAddresses accordingly.
// Replaces o.R.MultiAddresses with related.
// Sets related.R.ConnectionEvents's MultiAddresses accordingly.
func (o *ConnectionEvent) SetMultiAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*MultiAddress) error {
	query := "delete from \"connection_events_x_multi_addresses\" where \"connection_event_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeMultiAddressesFromConnectionEventsSlice(o, related)
	if o.R != nil {
		o.R.MultiAddresses = nil
	}

	return o.AddMultiAddresses(ctx, exec, insert, related...)
}

// RemoveMultiAddresses relationships from objects passed in.
// Removes related items from R.MultiAddresses (uses pointer comparison, removal does not keep order)
// Sets related.R.ConnectionEvents.
func (o *ConnectionEvent) RemoveMultiAddresses(ctx context.Context, exec boil.ContextExecutor, related ...*MultiAddress) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"connection_events_x_multi_addresses\" where \"connection_event_id\" = $1 and \"multi_address_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeMultiAddressesFromConnectionEventsSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.MultiAddresses {
			if rel != ri {
				continue
			}

			ln := len(o.R.MultiAddresses)
			if ln > 1 && i < ln-1 {
				o.R.MultiAddresses[i] = o.R.MultiAddresses[ln-1]
			}
			o.R.MultiAddresses = o.R.MultiAddresses[:ln-1]
			break
		}
	}

	return nil
}

func removeMultiAddressesFromConnectionEventsSlice(o *ConnectionEvent, related []*MultiAddress) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.ConnectionEvents {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.ConnectionEvents)
			if ln > 1 && i < ln-1 {
				rel.R.ConnectionEvents[i] = rel.R.ConnectionEvents[ln-1]
			}
			rel.R.ConnectionEvents = rel.R.ConnectionEvents[:ln-1]
			break
		}
	}
}

// ConnectionEvents retrieves all the records using an executor.
func ConnectionEvents(mods ...qm.QueryMod) connectionEventQuery {
	mods = append(mods, qm.From("\"connection_events\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"connection_events\".*"})
	}

	return connectionEventQuery{q}
}

// FindConnectionEvent retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindConnectionEvent(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*ConnectionEvent, error) {
	connectionEventObj := &ConnectionEvent{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"connection_events\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, connectionEventObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from connection_events")
	}

	if err = connectionEventObj.doAfterSelectHooks(ctx, exec); err != nil {
		return connectionEventObj, err
	}

	return connectionEventObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ConnectionEvent) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no connection_events provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(connectionEventColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	connectionEventInsertCacheMut.RLock()
	cache, cached := connectionEventInsertCache[key]
	connectionEventInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			connectionEventAllColumns,
			connectionEventColumnsWithDefault,
			connectionEventColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, connectionEventGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(connectionEventType, connectionEventMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(connectionEventType, connectionEventMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"connection_events\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"connection_events\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into connection_events")
	}

	if !cached {
		connectionEventInsertCacheMut.Lock()
		connectionEventInsertCache[key] = cache
		connectionEventInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ConnectionEvent.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ConnectionEvent) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	connectionEventUpdateCacheMut.RLock()
	cache, cached := connectionEventUpdateCache[key]
	connectionEventUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			connectionEventAllColumns,
			connectionEventPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, connectionEventGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update connection_events, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"connection_events\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, connectionEventPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(connectionEventType, connectionEventMapping, append(wl, connectionEventPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update connection_events row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for connection_events")
	}

	if !cached {
		connectionEventUpdateCacheMut.Lock()
		connectionEventUpdateCache[key] = cache
		connectionEventUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q connectionEventQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for connection_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for connection_events")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ConnectionEventSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), connectionEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"connection_events\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, connectionEventPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in connectionEvent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all connectionEvent")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ConnectionEvent) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no connection_events provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(connectionEventColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	connectionEventUpsertCacheMut.RLock()
	cache, cached := connectionEventUpsertCache[key]
	connectionEventUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			connectionEventAllColumns,
			connectionEventColumnsWithDefault,
			connectionEventColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			connectionEventAllColumns,
			connectionEventPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, connectionEventGeneratedColumns)
		update = strmangle.SetComplement(update, connectionEventGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert connection_events, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(connectionEventPrimaryKeyColumns))
			copy(conflict, connectionEventPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"connection_events\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(connectionEventType, connectionEventMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(connectionEventType, connectionEventMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert connection_events")
	}

	if !cached {
		connectionEventUpsertCacheMut.Lock()
		connectionEventUpsertCache[key] = cache
		connectionEventUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ConnectionEvent record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ConnectionEvent) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ConnectionEvent provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), connectionEventPrimaryKeyMapping)
	sql := "DELETE FROM \"connection_events\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from connection_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for connection_events")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q connectionEventQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no connectionEventQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from connection_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for connection_events")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ConnectionEventSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(connectionEventBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), connectionEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"connection_events\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, connectionEventPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from connectionEvent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for connection_events")
	}

	if len(connectionEventAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ConnectionEvent) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindConnectionEvent(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ConnectionEventSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ConnectionEventSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), connectionEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"connection_events\".* FROM \"connection_events\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, connectionEventPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ConnectionEventSlice")
	}

	*o = slice

	return nil
}

// ConnectionEventExists checks if the ConnectionEvent row exists.
func ConnectionEventExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"connection_events\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if connection_events exists")
	}

	return exists, nil
}
