// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MultiAddress is an object representing the database table.
type MultiAddress struct {
	ID             int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Maddr          string      `boil:"maddr" json:"maddr" toml:"maddr" yaml:"maddr"`
	Country        null.String `boil:"country" json:"country,omitempty" toml:"country" yaml:"country,omitempty"`
	Continent      null.String `boil:"continent" json:"continent,omitempty" toml:"continent" yaml:"continent,omitempty"`
	Asn            null.Int    `boil:"asn" json:"asn,omitempty" toml:"asn" yaml:"asn,omitempty"`
	IsPublic       bool        `boil:"is_public" json:"is_public" toml:"is_public" yaml:"is_public"`
	IsRelay        bool        `boil:"is_relay" json:"is_relay" toml:"is_relay" yaml:"is_relay"`
	IPAddressCount int         `boil:"ip_address_count" json:"ip_address_count" toml:"ip_address_count" yaml:"ip_address_count"`
	UpdatedAt      time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	CreatedAt      time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *multiAddressR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L multiAddressL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MultiAddressColumns = struct {
	ID             string
	Maddr          string
	Country        string
	Continent      string
	Asn            string
	IsPublic       string
	IsRelay        string
	IPAddressCount string
	UpdatedAt      string
	CreatedAt      string
}{
	ID:             "id",
	Maddr:          "maddr",
	Country:        "country",
	Continent:      "continent",
	Asn:            "asn",
	IsPublic:       "is_public",
	IsRelay:        "is_relay",
	IPAddressCount: "ip_address_count",
	UpdatedAt:      "updated_at",
	CreatedAt:      "created_at",
}

var MultiAddressTableColumns = struct {
	ID             string
	Maddr          string
	Country        string
	Continent      string
	Asn            string
	IsPublic       string
	IsRelay        string
	IPAddressCount string
	UpdatedAt      string
	CreatedAt      string
}{
	ID:             "multi_addresses.id",
	Maddr:          "multi_addresses.maddr",
	Country:        "multi_addresses.country",
	Continent:      "multi_addresses.continent",
	Asn:            "multi_addresses.asn",
	IsPublic:       "multi_addresses.is_public",
	IsRelay:        "multi_addresses.is_relay",
	IPAddressCount: "multi_addresses.ip_address_count",
	UpdatedAt:      "multi_addresses.updated_at",
	CreatedAt:      "multi_addresses.created_at",
}

// Generated where

var MultiAddressWhere = struct {
	ID             whereHelperint64
	Maddr          whereHelperstring
	Country        whereHelpernull_String
	Continent      whereHelpernull_String
	Asn            whereHelpernull_Int
	IsPublic       whereHelperbool
	IsRelay        whereHelperbool
	IPAddressCount whereHelperint
	UpdatedAt      whereHelpertime_Time
	CreatedAt      whereHelpertime_Time
}{
	ID:             whereHelperint64{field: "\"multi_addresses\".\"id\""},
	Maddr:          whereHelperstring{field: "\"multi_addresses\".\"maddr\""},
	Country:        whereHelpernull_String{field: "\"multi_addresses\".\"country\""},
	Continent:      whereHelpernull_String{field: "\"multi_addresses\".\"continent\""},
	Asn:            whereHelpernull_Int{field: "\"multi_addresses\".\"asn\""},
	IsPublic:       whereHelperbool{field: "\"multi_addresses\".\"is_public\""},
	IsRelay:        whereHelperbool{field: "\"multi_addresses\".\"is_relay\""},
	IPAddressCount: whereHelperint{field: "\"multi_addresses\".\"ip_address_count\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"multi_addresses\".\"updated_at\""},
	CreatedAt:      whereHelpertime_Time{field: "\"multi_addresses\".\"created_at\""},
}

// MultiAddressRels is where relationship names are stored.
var MultiAddressRels = struct {
	ConnectionMultiAddressConnectionEvents string
	ConnectionEvents                       string
	HolePunchAttempts                      string
	HolePunchResultsXMultiAddresses        string
	IPAddresses                            string
}{
	ConnectionMultiAddressConnectionEvents: "ConnectionMultiAddressConnectionEvents",
	ConnectionEvents:                       "ConnectionEvents",
	HolePunchAttempts:                      "HolePunchAttempts",
	HolePunchResultsXMultiAddresses:        "HolePunchResultsXMultiAddresses",
	IPAddresses:                            "IPAddresses",
}

// multiAddressR is where relationships are stored.
type multiAddressR struct {
	ConnectionMultiAddressConnectionEvents ConnectionEventSlice               `boil:"ConnectionMultiAddressConnectionEvents" json:"ConnectionMultiAddressConnectionEvents" toml:"ConnectionMultiAddressConnectionEvents" yaml:"ConnectionMultiAddressConnectionEvents"`
	ConnectionEvents                       ConnectionEventSlice               `boil:"ConnectionEvents" json:"ConnectionEvents" toml:"ConnectionEvents" yaml:"ConnectionEvents"`
	HolePunchAttempts                      HolePunchAttemptSlice              `boil:"HolePunchAttempts" json:"HolePunchAttempts" toml:"HolePunchAttempts" yaml:"HolePunchAttempts"`
	HolePunchResultsXMultiAddresses        HolePunchResultsXMultiAddressSlice `boil:"HolePunchResultsXMultiAddresses" json:"HolePunchResultsXMultiAddresses" toml:"HolePunchResultsXMultiAddresses" yaml:"HolePunchResultsXMultiAddresses"`
	IPAddresses                            IPAddressSlice                     `boil:"IPAddresses" json:"IPAddresses" toml:"IPAddresses" yaml:"IPAddresses"`
}

// NewStruct creates a new relationship struct
func (*multiAddressR) NewStruct() *multiAddressR {
	return &multiAddressR{}
}

// multiAddressL is where Load methods for each relationship are stored.
type multiAddressL struct{}

var (
	multiAddressAllColumns            = []string{"id", "maddr", "country", "continent", "asn", "is_public", "is_relay", "ip_address_count", "updated_at", "created_at"}
	multiAddressColumnsWithoutDefault = []string{"maddr", "country", "continent", "asn", "is_public", "is_relay", "ip_address_count", "updated_at", "created_at"}
	multiAddressColumnsWithDefault    = []string{"id"}
	multiAddressPrimaryKeyColumns     = []string{"id"}
)

type (
	// MultiAddressSlice is an alias for a slice of pointers to MultiAddress.
	// This should almost always be used instead of []MultiAddress.
	MultiAddressSlice []*MultiAddress
	// MultiAddressHook is the signature for custom MultiAddress hook methods
	MultiAddressHook func(context.Context, boil.ContextExecutor, *MultiAddress) error

	multiAddressQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	multiAddressType                 = reflect.TypeOf(&MultiAddress{})
	multiAddressMapping              = queries.MakeStructMapping(multiAddressType)
	multiAddressPrimaryKeyMapping, _ = queries.BindMapping(multiAddressType, multiAddressMapping, multiAddressPrimaryKeyColumns)
	multiAddressInsertCacheMut       sync.RWMutex
	multiAddressInsertCache          = make(map[string]insertCache)
	multiAddressUpdateCacheMut       sync.RWMutex
	multiAddressUpdateCache          = make(map[string]updateCache)
	multiAddressUpsertCacheMut       sync.RWMutex
	multiAddressUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var multiAddressBeforeInsertHooks []MultiAddressHook
var multiAddressBeforeUpdateHooks []MultiAddressHook
var multiAddressBeforeDeleteHooks []MultiAddressHook
var multiAddressBeforeUpsertHooks []MultiAddressHook

var multiAddressAfterInsertHooks []MultiAddressHook
var multiAddressAfterSelectHooks []MultiAddressHook
var multiAddressAfterUpdateHooks []MultiAddressHook
var multiAddressAfterDeleteHooks []MultiAddressHook
var multiAddressAfterUpsertHooks []MultiAddressHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MultiAddress) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range multiAddressBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MultiAddress) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range multiAddressBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MultiAddress) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range multiAddressBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MultiAddress) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range multiAddressBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MultiAddress) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range multiAddressAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MultiAddress) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range multiAddressAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MultiAddress) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range multiAddressAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MultiAddress) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range multiAddressAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MultiAddress) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range multiAddressAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMultiAddressHook registers your hook function for all future operations.
func AddMultiAddressHook(hookPoint boil.HookPoint, multiAddressHook MultiAddressHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		multiAddressBeforeInsertHooks = append(multiAddressBeforeInsertHooks, multiAddressHook)
	case boil.BeforeUpdateHook:
		multiAddressBeforeUpdateHooks = append(multiAddressBeforeUpdateHooks, multiAddressHook)
	case boil.BeforeDeleteHook:
		multiAddressBeforeDeleteHooks = append(multiAddressBeforeDeleteHooks, multiAddressHook)
	case boil.BeforeUpsertHook:
		multiAddressBeforeUpsertHooks = append(multiAddressBeforeUpsertHooks, multiAddressHook)
	case boil.AfterInsertHook:
		multiAddressAfterInsertHooks = append(multiAddressAfterInsertHooks, multiAddressHook)
	case boil.AfterSelectHook:
		multiAddressAfterSelectHooks = append(multiAddressAfterSelectHooks, multiAddressHook)
	case boil.AfterUpdateHook:
		multiAddressAfterUpdateHooks = append(multiAddressAfterUpdateHooks, multiAddressHook)
	case boil.AfterDeleteHook:
		multiAddressAfterDeleteHooks = append(multiAddressAfterDeleteHooks, multiAddressHook)
	case boil.AfterUpsertHook:
		multiAddressAfterUpsertHooks = append(multiAddressAfterUpsertHooks, multiAddressHook)
	}
}

// One returns a single multiAddress record from the query.
func (q multiAddressQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MultiAddress, error) {
	o := &MultiAddress{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for multi_addresses")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MultiAddress records from the query.
func (q multiAddressQuery) All(ctx context.Context, exec boil.ContextExecutor) (MultiAddressSlice, error) {
	var o []*MultiAddress

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MultiAddress slice")
	}

	if len(multiAddressAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MultiAddress records in the query.
func (q multiAddressQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count multi_addresses rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q multiAddressQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if multi_addresses exists")
	}

	return count > 0, nil
}

// ConnectionMultiAddressConnectionEvents retrieves all the connection_event's ConnectionEvents with an executor via connection_multi_address_id column.
func (o *MultiAddress) ConnectionMultiAddressConnectionEvents(mods ...qm.QueryMod) connectionEventQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"connection_events\".\"connection_multi_address_id\"=?", o.ID),
	)

	query := ConnectionEvents(queryMods...)
	queries.SetFrom(query.Query, "\"connection_events\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"connection_events\".*"})
	}

	return query
}

// ConnectionEvents retrieves all the connection_event's ConnectionEvents with an executor.
func (o *MultiAddress) ConnectionEvents(mods ...qm.QueryMod) connectionEventQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"connection_events_x_multi_addresses\" on \"connection_events\".\"id\" = \"connection_events_x_multi_addresses\".\"connection_event_id\""),
		qm.Where("\"connection_events_x_multi_addresses\".\"multi_address_id\"=?", o.ID),
	)

	query := ConnectionEvents(queryMods...)
	queries.SetFrom(query.Query, "\"connection_events\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"connection_events\".*"})
	}

	return query
}

// HolePunchAttempts retrieves all the hole_punch_attempt's HolePunchAttempts with an executor.
func (o *MultiAddress) HolePunchAttempts(mods ...qm.QueryMod) holePunchAttemptQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"hole_punch_attempt_x_multi_addresses\" on \"hole_punch_attempt\".\"id\" = \"hole_punch_attempt_x_multi_addresses\".\"hole_punch_attempt\""),
		qm.Where("\"hole_punch_attempt_x_multi_addresses\".\"multi_address_id\"=?", o.ID),
	)

	query := HolePunchAttempts(queryMods...)
	queries.SetFrom(query.Query, "\"hole_punch_attempt\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"hole_punch_attempt\".*"})
	}

	return query
}

// HolePunchResultsXMultiAddresses retrieves all the hole_punch_results_x_multi_address's HolePunchResultsXMultiAddresses with an executor.
func (o *MultiAddress) HolePunchResultsXMultiAddresses(mods ...qm.QueryMod) holePunchResultsXMultiAddressQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"hole_punch_results_x_multi_addresses\".\"multi_address_id\"=?", o.ID),
	)

	query := HolePunchResultsXMultiAddresses(queryMods...)
	queries.SetFrom(query.Query, "\"hole_punch_results_x_multi_addresses\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"hole_punch_results_x_multi_addresses\".*"})
	}

	return query
}

// IPAddresses retrieves all the ip_address's IPAddresses with an executor.
func (o *MultiAddress) IPAddresses(mods ...qm.QueryMod) ipAddressQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"multi_addresses_x_ip_addresses\" on \"ip_addresses\".\"id\" = \"multi_addresses_x_ip_addresses\".\"ip_address_id\""),
		qm.Where("\"multi_addresses_x_ip_addresses\".\"multi_address_id\"=?", o.ID),
	)

	query := IPAddresses(queryMods...)
	queries.SetFrom(query.Query, "\"ip_addresses\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"ip_addresses\".*"})
	}

	return query
}

// LoadConnectionMultiAddressConnectionEvents allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (multiAddressL) LoadConnectionMultiAddressConnectionEvents(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMultiAddress interface{}, mods queries.Applicator) error {
	var slice []*MultiAddress
	var object *MultiAddress

	if singular {
		object = maybeMultiAddress.(*MultiAddress)
	} else {
		slice = *maybeMultiAddress.(*[]*MultiAddress)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &multiAddressR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &multiAddressR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`connection_events`),
		qm.WhereIn(`connection_events.connection_multi_address_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load connection_events")
	}

	var resultSlice []*ConnectionEvent
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice connection_events")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on connection_events")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for connection_events")
	}

	if len(connectionEventAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ConnectionMultiAddressConnectionEvents = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &connectionEventR{}
			}
			foreign.R.ConnectionMultiAddress = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ConnectionMultiAddressID {
				local.R.ConnectionMultiAddressConnectionEvents = append(local.R.ConnectionMultiAddressConnectionEvents, foreign)
				if foreign.R == nil {
					foreign.R = &connectionEventR{}
				}
				foreign.R.ConnectionMultiAddress = local
				break
			}
		}
	}

	return nil
}

// LoadConnectionEvents allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (multiAddressL) LoadConnectionEvents(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMultiAddress interface{}, mods queries.Applicator) error {
	var slice []*MultiAddress
	var object *MultiAddress

	if singular {
		object = maybeMultiAddress.(*MultiAddress)
	} else {
		slice = *maybeMultiAddress.(*[]*MultiAddress)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &multiAddressR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &multiAddressR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.Select("\"connection_events\".id, \"connection_events\".local_id, \"connection_events\".remote_id, \"connection_events\".connection_multi_address_id, \"connection_events\".direction, \"connection_events\".listens_on_relay_multi_address, \"connection_events\".supports_dcutr, \"connection_events\".opened_at, \"connection_events\".created_at, \"a\".\"multi_address_id\""),
		qm.From("\"connection_events\""),
		qm.InnerJoin("\"connection_events_x_multi_addresses\" as \"a\" on \"connection_events\".\"id\" = \"a\".\"connection_event_id\""),
		qm.WhereIn("\"a\".\"multi_address_id\" in ?", args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load connection_events")
	}

	var resultSlice []*ConnectionEvent

	var localJoinCols []int64
	for results.Next() {
		one := new(ConnectionEvent)
		var localJoinCol int64

		err = results.Scan(&one.ID, &one.LocalID, &one.RemoteID, &one.ConnectionMultiAddressID, &one.Direction, &one.ListensOnRelayMultiAddress, &one.SupportsDcutr, &one.OpenedAt, &one.CreatedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for connection_events")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice connection_events")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on connection_events")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for connection_events")
	}

	if len(connectionEventAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ConnectionEvents = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &connectionEventR{}
			}
			foreign.R.MultiAddresses = append(foreign.R.MultiAddresses, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.ConnectionEvents = append(local.R.ConnectionEvents, foreign)
				if foreign.R == nil {
					foreign.R = &connectionEventR{}
				}
				foreign.R.MultiAddresses = append(foreign.R.MultiAddresses, local)
				break
			}
		}
	}

	return nil
}

// LoadHolePunchAttempts allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (multiAddressL) LoadHolePunchAttempts(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMultiAddress interface{}, mods queries.Applicator) error {
	var slice []*MultiAddress
	var object *MultiAddress

	if singular {
		object = maybeMultiAddress.(*MultiAddress)
	} else {
		slice = *maybeMultiAddress.(*[]*MultiAddress)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &multiAddressR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &multiAddressR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.Select("\"hole_punch_attempt\".id, \"hole_punch_attempt\".hole_punch_result_id, \"hole_punch_attempt\".opened_at, \"hole_punch_attempt\".started_at, \"hole_punch_attempt\".ended_at, \"hole_punch_attempt\".start_rtt, \"hole_punch_attempt\".elapsed_time, \"hole_punch_attempt\".outcome, \"hole_punch_attempt\".error, \"hole_punch_attempt\".direct_dial_error, \"hole_punch_attempt\".updated_at, \"hole_punch_attempt\".created_at, \"a\".\"multi_address_id\""),
		qm.From("\"hole_punch_attempt\""),
		qm.InnerJoin("\"hole_punch_attempt_x_multi_addresses\" as \"a\" on \"hole_punch_attempt\".\"id\" = \"a\".\"hole_punch_attempt\""),
		qm.WhereIn("\"a\".\"multi_address_id\" in ?", args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load hole_punch_attempt")
	}

	var resultSlice []*HolePunchAttempt

	var localJoinCols []int64
	for results.Next() {
		one := new(HolePunchAttempt)
		var localJoinCol int64

		err = results.Scan(&one.ID, &one.HolePunchResultID, &one.OpenedAt, &one.StartedAt, &one.EndedAt, &one.StartRTT, &one.ElapsedTime, &one.Outcome, &one.Error, &one.DirectDialError, &one.UpdatedAt, &one.CreatedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for hole_punch_attempt")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice hole_punch_attempt")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on hole_punch_attempt")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for hole_punch_attempt")
	}

	if len(holePunchAttemptAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.HolePunchAttempts = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &holePunchAttemptR{}
			}
			foreign.R.MultiAddresses = append(foreign.R.MultiAddresses, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.HolePunchAttempts = append(local.R.HolePunchAttempts, foreign)
				if foreign.R == nil {
					foreign.R = &holePunchAttemptR{}
				}
				foreign.R.MultiAddresses = append(foreign.R.MultiAddresses, local)
				break
			}
		}
	}

	return nil
}

// LoadHolePunchResultsXMultiAddresses allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (multiAddressL) LoadHolePunchResultsXMultiAddresses(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMultiAddress interface{}, mods queries.Applicator) error {
	var slice []*MultiAddress
	var object *MultiAddress

	if singular {
		object = maybeMultiAddress.(*MultiAddress)
	} else {
		slice = *maybeMultiAddress.(*[]*MultiAddress)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &multiAddressR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &multiAddressR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`hole_punch_results_x_multi_addresses`),
		qm.WhereIn(`hole_punch_results_x_multi_addresses.multi_address_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load hole_punch_results_x_multi_addresses")
	}

	var resultSlice []*HolePunchResultsXMultiAddress
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice hole_punch_results_x_multi_addresses")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on hole_punch_results_x_multi_addresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for hole_punch_results_x_multi_addresses")
	}

	if len(holePunchResultsXMultiAddressAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.HolePunchResultsXMultiAddresses = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &holePunchResultsXMultiAddressR{}
			}
			foreign.R.MultiAddress = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.MultiAddressID {
				local.R.HolePunchResultsXMultiAddresses = append(local.R.HolePunchResultsXMultiAddresses, foreign)
				if foreign.R == nil {
					foreign.R = &holePunchResultsXMultiAddressR{}
				}
				foreign.R.MultiAddress = local
				break
			}
		}
	}

	return nil
}

// LoadIPAddresses allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (multiAddressL) LoadIPAddresses(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMultiAddress interface{}, mods queries.Applicator) error {
	var slice []*MultiAddress
	var object *MultiAddress

	if singular {
		object = maybeMultiAddress.(*MultiAddress)
	} else {
		slice = *maybeMultiAddress.(*[]*MultiAddress)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &multiAddressR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &multiAddressR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.Select("\"ip_addresses\".id, \"ip_addresses\".address, \"ip_addresses\".country, \"ip_addresses\".continent, \"ip_addresses\".asn, \"ip_addresses\".is_public, \"ip_addresses\".updated_at, \"ip_addresses\".created_at, \"a\".\"multi_address_id\""),
		qm.From("\"ip_addresses\""),
		qm.InnerJoin("\"multi_addresses_x_ip_addresses\" as \"a\" on \"ip_addresses\".\"id\" = \"a\".\"ip_address_id\""),
		qm.WhereIn("\"a\".\"multi_address_id\" in ?", args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ip_addresses")
	}

	var resultSlice []*IPAddress

	var localJoinCols []int64
	for results.Next() {
		one := new(IPAddress)
		var localJoinCol int64

		err = results.Scan(&one.ID, &one.Address, &one.Country, &one.Continent, &one.Asn, &one.IsPublic, &one.UpdatedAt, &one.CreatedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for ip_addresses")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice ip_addresses")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on ip_addresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for ip_addresses")
	}

	if len(ipAddressAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.IPAddresses = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &ipAddressR{}
			}
			foreign.R.MultiAddresses = append(foreign.R.MultiAddresses, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.IPAddresses = append(local.R.IPAddresses, foreign)
				if foreign.R == nil {
					foreign.R = &ipAddressR{}
				}
				foreign.R.MultiAddresses = append(foreign.R.MultiAddresses, local)
				break
			}
		}
	}

	return nil
}

// AddConnectionMultiAddressConnectionEvents adds the given related objects to the existing relationships
// of the multi_address, optionally inserting them as new records.
// Appends related to o.R.ConnectionMultiAddressConnectionEvents.
// Sets related.R.ConnectionMultiAddress appropriately.
func (o *MultiAddress) AddConnectionMultiAddressConnectionEvents(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ConnectionEvent) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ConnectionMultiAddressID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"connection_events\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"connection_multi_address_id"}),
				strmangle.WhereClause("\"", "\"", 2, connectionEventPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ConnectionMultiAddressID = o.ID
		}
	}

	if o.R == nil {
		o.R = &multiAddressR{
			ConnectionMultiAddressConnectionEvents: related,
		}
	} else {
		o.R.ConnectionMultiAddressConnectionEvents = append(o.R.ConnectionMultiAddressConnectionEvents, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &connectionEventR{
				ConnectionMultiAddress: o,
			}
		} else {
			rel.R.ConnectionMultiAddress = o
		}
	}
	return nil
}

// AddConnectionEvents adds the given related objects to the existing relationships
// of the multi_address, optionally inserting them as new records.
// Appends related to o.R.ConnectionEvents.
// Sets related.R.MultiAddresses appropriately.
func (o *MultiAddress) AddConnectionEvents(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ConnectionEvent) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"connection_events_x_multi_addresses\" (\"multi_address_id\", \"connection_event_id\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &multiAddressR{
			ConnectionEvents: related,
		}
	} else {
		o.R.ConnectionEvents = append(o.R.ConnectionEvents, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &connectionEventR{
				MultiAddresses: MultiAddressSlice{o},
			}
		} else {
			rel.R.MultiAddresses = append(rel.R.MultiAddresses, o)
		}
	}
	return nil
}

// SetConnectionEvents removes all previously related items of the
// multi_address replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.MultiAddresses's ConnectionEvents accordingly.
// Replaces o.R.ConnectionEvents with related.
// Sets related.R.MultiAddresses's ConnectionEvents accordingly.
func (o *MultiAddress) SetConnectionEvents(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ConnectionEvent) error {
	query := "delete from \"connection_events_x_multi_addresses\" where \"multi_address_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeConnectionEventsFromMultiAddressesSlice(o, related)
	if o.R != nil {
		o.R.ConnectionEvents = nil
	}
	return o.AddConnectionEvents(ctx, exec, insert, related...)
}

// RemoveConnectionEvents relationships from objects passed in.
// Removes related items from R.ConnectionEvents (uses pointer comparison, removal does not keep order)
// Sets related.R.MultiAddresses.
func (o *MultiAddress) RemoveConnectionEvents(ctx context.Context, exec boil.ContextExecutor, related ...*ConnectionEvent) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"connection_events_x_multi_addresses\" where \"multi_address_id\" = $1 and \"connection_event_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeConnectionEventsFromMultiAddressesSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ConnectionEvents {
			if rel != ri {
				continue
			}

			ln := len(o.R.ConnectionEvents)
			if ln > 1 && i < ln-1 {
				o.R.ConnectionEvents[i] = o.R.ConnectionEvents[ln-1]
			}
			o.R.ConnectionEvents = o.R.ConnectionEvents[:ln-1]
			break
		}
	}

	return nil
}

func removeConnectionEventsFromMultiAddressesSlice(o *MultiAddress, related []*ConnectionEvent) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.MultiAddresses {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.MultiAddresses)
			if ln > 1 && i < ln-1 {
				rel.R.MultiAddresses[i] = rel.R.MultiAddresses[ln-1]
			}
			rel.R.MultiAddresses = rel.R.MultiAddresses[:ln-1]
			break
		}
	}
}

// AddHolePunchAttempts adds the given related objects to the existing relationships
// of the multi_address, optionally inserting them as new records.
// Appends related to o.R.HolePunchAttempts.
// Sets related.R.MultiAddresses appropriately.
func (o *MultiAddress) AddHolePunchAttempts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*HolePunchAttempt) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"hole_punch_attempt_x_multi_addresses\" (\"multi_address_id\", \"hole_punch_attempt\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &multiAddressR{
			HolePunchAttempts: related,
		}
	} else {
		o.R.HolePunchAttempts = append(o.R.HolePunchAttempts, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &holePunchAttemptR{
				MultiAddresses: MultiAddressSlice{o},
			}
		} else {
			rel.R.MultiAddresses = append(rel.R.MultiAddresses, o)
		}
	}
	return nil
}

// SetHolePunchAttempts removes all previously related items of the
// multi_address replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.MultiAddresses's HolePunchAttempts accordingly.
// Replaces o.R.HolePunchAttempts with related.
// Sets related.R.MultiAddresses's HolePunchAttempts accordingly.
func (o *MultiAddress) SetHolePunchAttempts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*HolePunchAttempt) error {
	query := "delete from \"hole_punch_attempt_x_multi_addresses\" where \"multi_address_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeHolePunchAttemptsFromMultiAddressesSlice(o, related)
	if o.R != nil {
		o.R.HolePunchAttempts = nil
	}
	return o.AddHolePunchAttempts(ctx, exec, insert, related...)
}

// RemoveHolePunchAttempts relationships from objects passed in.
// Removes related items from R.HolePunchAttempts (uses pointer comparison, removal does not keep order)
// Sets related.R.MultiAddresses.
func (o *MultiAddress) RemoveHolePunchAttempts(ctx context.Context, exec boil.ContextExecutor, related ...*HolePunchAttempt) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"hole_punch_attempt_x_multi_addresses\" where \"multi_address_id\" = $1 and \"hole_punch_attempt\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeHolePunchAttemptsFromMultiAddressesSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.HolePunchAttempts {
			if rel != ri {
				continue
			}

			ln := len(o.R.HolePunchAttempts)
			if ln > 1 && i < ln-1 {
				o.R.HolePunchAttempts[i] = o.R.HolePunchAttempts[ln-1]
			}
			o.R.HolePunchAttempts = o.R.HolePunchAttempts[:ln-1]
			break
		}
	}

	return nil
}

func removeHolePunchAttemptsFromMultiAddressesSlice(o *MultiAddress, related []*HolePunchAttempt) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.MultiAddresses {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.MultiAddresses)
			if ln > 1 && i < ln-1 {
				rel.R.MultiAddresses[i] = rel.R.MultiAddresses[ln-1]
			}
			rel.R.MultiAddresses = rel.R.MultiAddresses[:ln-1]
			break
		}
	}
}

// AddHolePunchResultsXMultiAddresses adds the given related objects to the existing relationships
// of the multi_address, optionally inserting them as new records.
// Appends related to o.R.HolePunchResultsXMultiAddresses.
// Sets related.R.MultiAddress appropriately.
func (o *MultiAddress) AddHolePunchResultsXMultiAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*HolePunchResultsXMultiAddress) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.MultiAddressID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"hole_punch_results_x_multi_addresses\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"multi_address_id"}),
				strmangle.WhereClause("\"", "\"", 2, holePunchResultsXMultiAddressPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.MultiAddressID, rel.HolePunchResultID, rel.Relationship}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.MultiAddressID = o.ID
		}
	}

	if o.R == nil {
		o.R = &multiAddressR{
			HolePunchResultsXMultiAddresses: related,
		}
	} else {
		o.R.HolePunchResultsXMultiAddresses = append(o.R.HolePunchResultsXMultiAddresses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &holePunchResultsXMultiAddressR{
				MultiAddress: o,
			}
		} else {
			rel.R.MultiAddress = o
		}
	}
	return nil
}

// AddIPAddresses adds the given related objects to the existing relationships
// of the multi_address, optionally inserting them as new records.
// Appends related to o.R.IPAddresses.
// Sets related.R.MultiAddresses appropriately.
func (o *MultiAddress) AddIPAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IPAddress) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"multi_addresses_x_ip_addresses\" (\"multi_address_id\", \"ip_address_id\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &multiAddressR{
			IPAddresses: related,
		}
	} else {
		o.R.IPAddresses = append(o.R.IPAddresses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &ipAddressR{
				MultiAddresses: MultiAddressSlice{o},
			}
		} else {
			rel.R.MultiAddresses = append(rel.R.MultiAddresses, o)
		}
	}
	return nil
}

// SetIPAddresses removes all previously related items of the
// multi_address replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.MultiAddresses's IPAddresses accordingly.
// Replaces o.R.IPAddresses with related.
// Sets related.R.MultiAddresses's IPAddresses accordingly.
func (o *MultiAddress) SetIPAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IPAddress) error {
	query := "delete from \"multi_addresses_x_ip_addresses\" where \"multi_address_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeIPAddressesFromMultiAddressesSlice(o, related)
	if o.R != nil {
		o.R.IPAddresses = nil
	}
	return o.AddIPAddresses(ctx, exec, insert, related...)
}

// RemoveIPAddresses relationships from objects passed in.
// Removes related items from R.IPAddresses (uses pointer comparison, removal does not keep order)
// Sets related.R.MultiAddresses.
func (o *MultiAddress) RemoveIPAddresses(ctx context.Context, exec boil.ContextExecutor, related ...*IPAddress) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"multi_addresses_x_ip_addresses\" where \"multi_address_id\" = $1 and \"ip_address_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeIPAddressesFromMultiAddressesSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.IPAddresses {
			if rel != ri {
				continue
			}

			ln := len(o.R.IPAddresses)
			if ln > 1 && i < ln-1 {
				o.R.IPAddresses[i] = o.R.IPAddresses[ln-1]
			}
			o.R.IPAddresses = o.R.IPAddresses[:ln-1]
			break
		}
	}

	return nil
}

func removeIPAddressesFromMultiAddressesSlice(o *MultiAddress, related []*IPAddress) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.MultiAddresses {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.MultiAddresses)
			if ln > 1 && i < ln-1 {
				rel.R.MultiAddresses[i] = rel.R.MultiAddresses[ln-1]
			}
			rel.R.MultiAddresses = rel.R.MultiAddresses[:ln-1]
			break
		}
	}
}

// MultiAddresses retrieves all the records using an executor.
func MultiAddresses(mods ...qm.QueryMod) multiAddressQuery {
	mods = append(mods, qm.From("\"multi_addresses\""))
	return multiAddressQuery{NewQuery(mods...)}
}

// FindMultiAddress retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMultiAddress(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*MultiAddress, error) {
	multiAddressObj := &MultiAddress{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"multi_addresses\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, multiAddressObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from multi_addresses")
	}

	if err = multiAddressObj.doAfterSelectHooks(ctx, exec); err != nil {
		return multiAddressObj, err
	}

	return multiAddressObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MultiAddress) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no multi_addresses provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(multiAddressColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	multiAddressInsertCacheMut.RLock()
	cache, cached := multiAddressInsertCache[key]
	multiAddressInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			multiAddressAllColumns,
			multiAddressColumnsWithDefault,
			multiAddressColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(multiAddressType, multiAddressMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(multiAddressType, multiAddressMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"multi_addresses\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"multi_addresses\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into multi_addresses")
	}

	if !cached {
		multiAddressInsertCacheMut.Lock()
		multiAddressInsertCache[key] = cache
		multiAddressInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MultiAddress.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MultiAddress) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	multiAddressUpdateCacheMut.RLock()
	cache, cached := multiAddressUpdateCache[key]
	multiAddressUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			multiAddressAllColumns,
			multiAddressPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update multi_addresses, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"multi_addresses\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, multiAddressPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(multiAddressType, multiAddressMapping, append(wl, multiAddressPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update multi_addresses row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for multi_addresses")
	}

	if !cached {
		multiAddressUpdateCacheMut.Lock()
		multiAddressUpdateCache[key] = cache
		multiAddressUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q multiAddressQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for multi_addresses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for multi_addresses")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MultiAddressSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), multiAddressPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"multi_addresses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, multiAddressPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in multiAddress slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all multiAddress")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MultiAddress) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no multi_addresses provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(multiAddressColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	multiAddressUpsertCacheMut.RLock()
	cache, cached := multiAddressUpsertCache[key]
	multiAddressUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			multiAddressAllColumns,
			multiAddressColumnsWithDefault,
			multiAddressColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			multiAddressAllColumns,
			multiAddressPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert multi_addresses, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(multiAddressPrimaryKeyColumns))
			copy(conflict, multiAddressPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"multi_addresses\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(multiAddressType, multiAddressMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(multiAddressType, multiAddressMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert multi_addresses")
	}

	if !cached {
		multiAddressUpsertCacheMut.Lock()
		multiAddressUpsertCache[key] = cache
		multiAddressUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MultiAddress record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MultiAddress) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MultiAddress provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), multiAddressPrimaryKeyMapping)
	sql := "DELETE FROM \"multi_addresses\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from multi_addresses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for multi_addresses")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q multiAddressQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no multiAddressQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from multi_addresses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for multi_addresses")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MultiAddressSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(multiAddressBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), multiAddressPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"multi_addresses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, multiAddressPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from multiAddress slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for multi_addresses")
	}

	if len(multiAddressAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MultiAddress) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMultiAddress(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MultiAddressSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MultiAddressSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), multiAddressPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"multi_addresses\".* FROM \"multi_addresses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, multiAddressPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MultiAddressSlice")
	}

	*o = slice

	return nil
}

// MultiAddressExists checks if the MultiAddress row exists.
func MultiAddressExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"multi_addresses\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if multi_addresses exists")
	}

	return exists, nil
}
