{
 "title": "Punchr Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Inbound connections from DCUtR peers behind relays in the last 15m",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(DISTINCT ce.remote_id)\nFROM connection_events ce\nWHERE opened_at > NOW() - '15min'::INTERVAL \n  AND ce.supports_dcutr = true \n  AND ce.listens_on_relay_multi_address = true\n  AND ce.direction = 'INBOUND'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hole Punches Performed per 15m (bars are stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,15m),\n  count(id) AS \"Error\"\nFROM hole_punch_results\nWHERE\n  $__timeFilter(created_at) AND\n  outcome = 'SUCCESS'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,15m),\n  count(id) AS \"Success\"\nFROM hole_punch_results\nWHERE\n  $__timeFilter(created_at) AND\n  outcome != 'SUCCESS'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hole Punche Errors per 15m",
   "type": "timeseries",
   "description": "NO_CONNECTION: We could not connect to the remote peer through the advertised relay.\nCONNECTION_REVERSED: Connection reversal from the remote peer succeeded.\nNO_STREAM: We connected to the remote peer but it did not open the /libp2p/dcutr stream\nFAILED: Attempted hole punches but they failed.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,15m),\n  count(id) AS \"Error: NO_CONNECTION\"\nFROM hole_punch_results\nWHERE\n  $__timeFilter(created_at) AND\n  outcome = 'NO_CONNECTION'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,15m),\n  count(id) AS \"Error: CONNECTION_REVERSED\"\nFROM hole_punch_results\nWHERE\n  $__timeFilter(created_at) AND\n  outcome = 'CONNECTION_REVERSED'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,15m),\n  count(id) AS \"Error: NO_STREAM\"\nFROM hole_punch_results\nWHERE\n  $__timeFilter(created_at) AND\n  outcome = 'NO_STREAM'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,15m),\n  count(id) AS \"Error: FAILED\"\nFROM hole_punch_results\nWHERE\n  $__timeFilter(created_at) AND\n  outcome = 'FAILED'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Crawled peers per seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "irate(honeypot_crawled_peers{status=\"error\"}[5m])",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "irate(honeypot_crawled_peers{status=\"ok\"}[5m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Honeypot Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"punchr_honeypot\", instance=\"localhost:11001\"}"
    }
   ]
  },
  {
   "title": "Honeypot CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"punchr_honeypot\", instance=\"localhost:11001\"}[5m])"
    }
   ]
  },
  {
   "title": "Most Recent Hole Punch Results",
   "type": "table",
   "description": "NO_CONNECTION: We could not connect to the remote peer through the advertised relay\nNOT_INITIATED: We could connect to the remote peer but it did not initiate a hole punch in time (15s)\nHOLE_PUNCH: Hole punch was initiated by the remote buy it did not succeed",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  hpr.client_id \"Punchr Client\",\n  substring(p2.agent_version, 8) \"Client Agent\",\n  p.multi_hash \"Remote Peer ID\",\n  hpr.outcome \"Outcome\",\n  EXTRACT('epoch' FROM hpr.connect_ended_at - hpr.connect_started_at) \"Elapsed Time in s\",\n  (SELECT count(*) FROM hole_punch_attempt hpa WHERE hpa.hole_punch_result_id = hpr.id) \"Attempts\",\n  (SELECT array_agg(hpa.outcome) FROM hole_punch_attempt hpa WHERE hpa.hole_punch_result_id = hpr.id GROUP BY hpr.id) \"Attempt Outcomes\",\n  ma.maddr \"Multi Address\",\n  hpr.error \"Error\",\n  hpr.connect_started_at \"Connection Started At\"\nFROM hole_punch_results hpr\n  INNER JOIN peers p ON p.id = hpr.remote_id\n  INNER JOIN peers p2 ON p2.id = hpr.client_id\n  LEFT JOIN hole_punch_results_x_multi_addresses hprxma ON hprxma.hole_punch_result_id = hpr.id\n  LEFT JOIN multi_addresses ma ON ma.id = hprxma.multi_address_id\nWHERE hprxma.relationship = 'INITIAL'\nORDER BY hpr.connect_started_at DESC\nLIMIT 100\n"
    }
   ]
  }
 ]
}